version: '3'

services:
  app:
    image: blog-app:latest
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      SERVER_PORT: 3000
      MONGO_URI: mongodb://db:27017

  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"